# Generated by Django 2.1.3 on 2019-02-11 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=100)),
                ('completion_condition', models.CharField(blank=True, help_text="Keywords: <span class='keyword'>AND</span>, <span class='keyword'>OR</span>.</br>Operations: <, >, =</br>Variables: <span class='variable'>price</span>, <span class='variable'>quantity</span></br>Use parentheses to group statements.</br></br>Example:</br> (<span class='variable'>price</span> < 100 <span class='keyword'>AND</span> (<span class='variable'>quantity</span> > 20 <span class='keyword'>AND</span> <span class='variable'>quantity</span> < 50)) </br><span class='keyword'>OR</span> (<span class='variable'>price</span> < 120 <span class='keyword'>AND</span> <span class='variable'>quantity</span> < 20)", max_length=256)),
                ('unit', models.CharField(max_length=10)),
                ('currency', models.CharField(choices=[('GBP', 'GBP'), ('USD', 'USD'), ('BTC', 'BTC')], default='GBP', max_length=3)),
                ('contract_type', models.CharField(choices=[('Buy', 'BUY'), ('Sell', 'SELL')], default='Buy', max_length=4)),
                ('location', models.CharField(max_length=8)),
                ('completion_date', models.DateField()),
                ('contract', models.TextField()),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
