# Generated by Django 2.1.3 on 2019-03-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190211_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='location',
        ),
    ]
