# Generated by Django 2.1.7 on 2019-03-03 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0006_auto_20190303_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generatedId', models.CharField(max_length=12)),
                ('assetAddress', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=8)),
                ('transferTime', models.IntegerField(default=0)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_carrier', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generatedId', models.CharField(max_length=12)),
                ('assetAddress', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('Transit', 'TRANSIT'), ('Delivered', 'DELIVERED'), ('Confirmed', 'CONFIRMED')], default='Transit', max_length=9)),
                ('owed', models.DecimalField(decimal_places=18, default=0, max_digits=20)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='offer',
            name='bounds',
            field=models.CharField(default='0,2147483648,0,2147483648', max_length=256),
        ),
    ]
