# Generated by Django 2.1.7 on 2019-03-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20190303_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='transactionStatus',
            field=models.CharField(choices=[('SUBMITTED', 'SUBMITTED'), ('SUCCESS', 'SUCCESS'), ('FAIL', 'FAIL')], default='SUBMITTED', max_length=9),
        ),
    ]
