# Generated by Django 2.1.7 on 2019-03-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_asset_transactionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='owed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('Processing', 'PROCESSING'), ('Transaction Failed', 'TRANSACTION FAILED'), ('TRANSIT', 'TRANSIT'), ('Delivered', 'DELIVERED'), ('Confirmed', 'CONFIRMED')], default='Processing', max_length=18),
        ),
    ]
