# Generated by Django 2.1.7 on 2019-03-04 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_wallet_ether_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='assetAddress',
        ),
        migrations.AddField(
            model_name='record',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.Asset'),
        ),
    ]
