# Generated by Django 2.1.3 on 2019-04-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20190304_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='stock',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='contract_type',
            field=models.CharField(choices=[('Buy', 'BUY'), ('Sell', 'SELL')], default='Sell', max_length=4),
        ),
    ]
