# Generated by Django 2.1.3 on 2019-04-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20190425_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='stock',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=20),
        ),
    ]
