# Generated by Django 2.1.3 on 2019-04-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20190427_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='private_key',
            field=models.CharField(max_length=450),
        ),
        migrations.AlterField(
            model_name='profile',
            name='public_key',
            field=models.CharField(max_length=1674),
        ),
    ]
